Admin/urls.py
from django.urls import path
from Admin.views import *

app_name = 'admin'

urlpatterns = [
    path('', index_view, name='index-view'),
    path('profile/', profile_view, name='profile-view'),
    path('create/teacher/', create_teacher_view, name='create-teacher-view'),
    path('update/teacher/<int:user_id>/', update_teacher_view, name='update-teacher-view'),
    path('list/<str:role>/', list_users_view, name='list-users-view')
]

Course/urls.py
from django.urls import path
from Course.views import *

app_name = 'course'

urlpatterns = [
    path('create/', create_course_view, name='create-course-view'),    
    path('update/<int:course_id>/', update_course_view, name='update-course-view'),    
    path('delete/<int:course_id>/', delete_course_view, name='delete-course-view'),
    path('detail/<int:course_id>/', detail_course_view, name='detail-course-view'),
    path('list/courses/', list_courses_view, name='list-courses-view'),
    path('save/curriculum/<int:course_id>/', save_curriculum_view, name='save-curriculum-view'),
    path('detail/exam/<int:course_id>/', detail_exam_view, name='detail-exam-view')
]

EasyLearnApp/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('Users.urls')),
    path('admin/', include('Admin.urls', namespace='admin')),
    path('teacher/', include('Teacher.urls', namespace='teacher')),
    path('course/', include('Course.urls', namespace='course')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Teacher/urls.py
from django.urls import path
from Teacher.views import *

app_name = 'teacher'

urlpatterns = [
    path('', index_view, name='index-view'),
    path('profile/', profile_view, name='profile-view'),
    path('list/Student/', list_students_view, name='list-students-view'),
]

Teacher/models.py
from django.db import models

# Create your models here.

Teacher/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib import messages
from Users.models import *
from Course.models import *
# Create your views here.

def index_view(request):
    user_courses = Course.objects.filter(created_by=request.user).all()
    total_courses = user_courses.count()
    
    total_videos = Lesson.objects.filter(
        curriculum_item__section__curriculum__course__created_by=request.user
    ).count()

    total_notes = Lesson.objects.filter(
        curriculum_item__section__curriculum__course__created_by=request.user,
        note_file__isnull=False
    ).exclude(note_file='').count()

    total_quizzes = Quiz.objects.filter(
        curriculum_item__section__curriculum__course__created_by=request.user
    ).count()

    unique_student_count = WatchedContent.objects.filter(
        item__section__curriculum__course__created_by=request.user
    ).values('user').distinct().count()


    unique_result_students = Result.objects.filter(
        course__created_by=request.user
    ).values('user').distinct().count()

    context = {
        "total_courses":total_courses,
        "total_videos":total_videos,
        "total_notes":total_notes,
        "total_quizzes":total_quizzes,
        "unique_student_count":unique_student_count,
        "unique_result_students":unique_result_students
    }

    return render(request, 'teacher/index.html', context=context)

def profile_view(request):
    if request.method == 'POST':
        try:
            profile_photo = request.FILES.get('profile_photo', '')
            first_name = request.POST.get('first_name')
            last_name = request.POST.get('last_name')
            email = request.POST.get('email')
            phone_number = request.POST.get('phone_number')

            user = request.user

            if User.objects.filter(email=email).exists():
                if email != request.user.email:
                    return JsonResponse({'status':'error', 'message':f'Email address already exists.'})

            if Profile.objects.filter(phone_number=phone_number).exists():
                if phone_number != request.user.profile.phone_number:
                    return JsonResponse({'status':'error', 'message':'Phone number already exists.'})

            user.profile_photo = profile_photo if profile_photo != '' else user.profile_photo
            user.first_name = first_name
            user.last_name = last_name
            user.email = email
            user.save()

            profile = Profile.objects.get(user=user)
            profile.phone_number = phone_number
            profile.save()

            messages.success(request, f'{user.first_name} {user.last_name[0]} profile saved successfully.')
            return JsonResponse({'status':'success', 'success_url':'/teacher/profile/'})

        except Exception as error:
            return JsonResponse({'status':'error', 'message':f'ERROR: {error}'})
    return render(request, 'teacher/profile.html')

def list_students_view(request):
    users = User.objects.filter(role='Student')
    return render(request, 'teacher/list_students.html', context={'users':users})

Teacher/templates/teacher/base_site.html
{% extends "users/base.html" %}
{% load static %}

{% block content %}

    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
            <a href="{% url "teacher:index-view" %}" class="logo">
                <span class="text-dark">
                    <i class="bi bi-mortarboard-fill"></i>
                    <span class="text-primary">EASY</span>
                    LEARN
                </span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div>

        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">

                <li class="nav-item dropdown pe-3">

                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <img src="{{request.user.profile_photo.url}}" alt="Profile" class="rounded-circle" style="width:35px; height:35px; object-position: center;">
                        <span class="d-none d-md-block dropdown-toggle fs-5 ps-2">{{request.user.first_name}} {{request.user.last_name.0}}</span>
                    </a>

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">

                        <li class="dropdown-header">
                            <h6>{{request.user.first_name}} {{request.user.last_name}}</h6>
                            <span>{{request.user.email}}</span>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="{% url "teacher:profile-view" %}">
                                <i class="bi bi-person"></i>
                                <span>My Profile</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="{% url "logout-view" %}">
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Sign Out</span>
                            </a>
                        </li>
                    </ul>

                </li>

            </ul>
        </nav>

    </header>

    <aside id="sidebar" class="sidebar bg-primary-subtle">
        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item mb-4">
                <a href="{% url "teacher:index-view" %}" class="nav-link {% if request.resolver_match.url_name == 'index-view' %} active bg-dark {% endif %}">
                    <i class="bi bi-house-door-fill"></i>
                    <span>HOME</span>
                </a>
            </li>

            <li class="nav-heading">COURSES</li>

            <li class="nav-item mb-4">
                <a href="{% url "course:create-course-view" %}" class="nav-link {% if request.resolver_match.url_name == 'create-course-view' %} active bg-dark{% endif %} collapsed">
                    <i class="bi bi-journal-bookmark-fill"></i>
                    <span>CREATE COURSE</span>
                </a>
            </li>

            <li class="nav-item mt-4">
                <a href="{% url "course:list-courses-view" %}" class="nav-link {% if request.resolver_match.url_name == 'list-courses-view' %} active bg-dark{% endif %} collapsed">
                    <i class="bi bi-journal-text"></i>
                    <span>LIST COURSE'S</span>
                </a>
            </li>

            <li class="nav-heading">STUDENT</li>

            <li class="nav-item">
                <a href="{% url "teacher:list-students-view" %}" class="nav-link {% if request.resolver_match.url_name == 'list-students-view' %}active bg-dark{% endif %}">
                    <i class="bi bi-person-lines-fill"></i>
                    <span>LIST STUDENT'S</span>
                </a>
            </li>

        </ul>
    </aside>

    {% block main %}{% endblock main %}

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

{% endblock content %}

Teacher/templates/teacher/index.html
{% extends "teacher/base_site.html" %}

{% block title %} Home {% endblock title %} 

{% block main %}

    <main id="main" class="main">

        {% include "components/alert.html" %}

        <section class="section">


            <div class="pagetitle">
                <h1>
                    <i class="bi bi-speedometer2"></i>
                    DASHBOARD
                </h1>
            </div>
            
            <div class="row">

                <div class="col-4">

                    <div class="card bg-danger-subtle rounded rounded-4 shadow">
                        <div class="card-body text-center">
                            <h5 class="card-title text-dark fs-5">YOUR COURSES</h5>
                            <span class="badge text-bg-light fs-5">{{total_courses}}</span>
                        </div>
                    </div>

                </div>

                <div class="col-4">

                    <div class="card bg-primary-subtle rounded rounded-4 shadow">
                        <div class="card-body text-center">
                            <h5 class="card-title text-dark fs-5">TOTAL VIDEOS</h5>
                            <span class="badge text-bg-light fs-5">{{total_videos}}</span>
                        </div>
                    </div>

                </div>

                <div class="col-4">

                    <div class="card bg-success-subtle rounded rounded-4 shadow">
                        <div class="card-body text-center">
                            <h5 class="card-title text-dark fs-5">TOTAL NOTES</h5>
                            <span class="badge text-bg-light fs-5">{{total_notes}}</span>
                        </div>
                    </div>

                </div>

                <div class="col-4">

                    <div class="card bg-success-subtle rounded rounded-4 shadow">
                        <div class="card-body text-center">
                            <h5 class="card-title text-dark fs-5">TOTAL QUIZZES</h5>
                            <span class="badge text-bg-light fs-5">{{total_quizzes}}</span>
                        </div>
                    </div>

                </div>

                <div class="col-4">

                    <div class="card bg-danger-subtle rounded rounded-4 shadow">
                        <div class="card-body text-center">
                            <h5 class="card-title text-dark fs-5">UNIQUE VIEWS</h5>
                            <span class="badge text-bg-light fs-5">{{unique_student_count}}</span>
                        </div>
                    </div>

                </div>

                <div class="col-4">

                    <div class="card bg-primary-subtle rounded rounded-4 shadow">
                        <div class="card-body text-center">
                            <h5 class="card-title text-dark fs-5">PASSED STUDENTS</h5>
                            <span class="badge text-bg-light fs-5">{{unique_result_students}}</span>
                        </div>
                    </div>

                </div>



            </div>

        </section>

    </main>


{% endblock main %}

Teacher/templates/teacher/list_students.html
{% extends "teacher/base_site.html" %}

{% block title %} List Student {% endblock title %}

{% block main %}
    <main id="main" class="main">
        
        <section class="section">

            <div class="row justify-content-center">
                <div class="col col-lg-12">

                    <div class="card">
                        <div class="card-body">

                            <h5 class="card-title text-center">
                                <i class="bi bi-person-lines-fill"></i>
                                LIST STUDENT PROFILE'S
                            </h5>

                            {% include "components/alert.html" %}

                            <table class="table datatable">

                                <thead >
                                    <tr>
                                        <th>ID</th>
                                        <th class="d-none d-lg-table-cell"><b>F</b>ULL NAME</th>
                                        <th class="d-none d-lg-table-cell">EMAIL</th>
                                        <th class="d-none d-lg-table-cell">INSTITUTE</th>
                                        <th>DELETE</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    {% for user in users %}
                                        <tr>
                                            <td>{{user.id}}</td>
                                            <td class="d-none d-lg-table-cell">{{user.first_name}} {{user.last_name}}</td>
                                            <td class="d-none d-lg-table-cell">{{user.email}}</td>
                                            <td class="d-none d-lg-table-cell">{{user.institute}}</td>
                                            <td>
                                                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#verticalycentered{{user.id}}">
                                                    <i class="bi bi-trash"></i>
                                                </button>

                                                <div class="modal fade" id="verticalycentered{{user.id}}" tabindex="-1">
                                                    <div class="modal-dialog modal-dialog-centered">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h5 class="modal-title">Confirm Delete</h5>
                                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                            </div>
                                                            <div class="modal-body">
                                                                Are sure you want to delete <strong>{{user.id}}:{{user.first_name}} {{user.last_name}}</strong> ?
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                                                <a href="{% url "delete-user-view" user.id %}" class="btn btn-danger">Delete</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>

                        </div>
                    </div>

                </div>
            </div>

        </section>

    </main>
{% endblock main %}

    

Teacher/templates/teacher/profile.html
{% extends "teacher/base_site.html" %}
{% load static %}

{% block title %} Profile {% endblock title %}

{% block main %}

    <main id="main" class="main">

        <section class="section profile">

            <div class="row">

                <div class="col-12">
                    <div class="card bg-transparent">
                        <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">

                            {% if request.user.profile_photo %}
                                <img src="{{user.profile_photo.url}}" alt="Profile" class="rounded-circle" style="width:120px; height:120px; object-position: center;">
                            {% else %}
                                <img src="{% static "users/img/profile.jpg" %}" alt="Profile" class="rounded-circle border" style="width:120px; height:120px; object-position: center;">
                            {% endif %}
                            
                            <h2>{{request.user.first_name}} {{request.user.last_name}}</h2>
                            <p>{{request.user.role}}</p>
                        </div>
                    </div>
                </div>

                <div class="col-12">
                    <div class="card">
                        <div class="card-body pt-3">

                            <!-- Bordered Tabs -->
                            <ul class="nav nav-tabs nav-tabs-bordered">
                                <li class="nav-item">
                                    <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">Overview</button>
                                </li>
                
                                <li class="nav-item">
                                    <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit">Edit Profile</button>
                                </li>
                
                                <li class="nav-item">
                                    <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-change-password">Change Password</button>
                                </li>
                            </ul>

                            <div class="tab-content pt-2">
                                
                                {% include "components/alert.html" %}

                                <!-- Profile Details -->
                                <div class="tab-pane fade show active profile-overview" id="profile-overview">
                
                                    <h5 class="card-title">{{request.user.role|upper}} PROFILE DETAILS</h5>
                
                                    <div class="row">
                                        <div class="col-lg-3 col-md-4 label ">Full Name</div>
                                        <div class="col-lg-9 col-md-8">{{request.user.first_name}} {{request.user.last_name}}</div>
                                    </div>
                
                                    <div class="row">
                                        <div class="col-lg-3 col-md-4 label">Email</div>
                                        <div class="col-lg-9 col-md-8">{{request.user.email}}</div>
                                    </div>
                
                                    <div class="row">
                                        <div class="col-lg-3 col-md-4 label">Phone Number</div>
                                        <div class="col-lg-9 col-md-8">(+91) {{request.user.profile.phone_number}}</div>
                                    </div>

                                    <div class="row">
                                        <div class="col-lg-3 col-md-4 label">Experince</div>
                                        <div class="col-lg-9 col-md-8">{{request.user.profile.experience}}</div>
                                    </div>
                
                                    <div class="row">
                                        <div class="col-lg-3 col-md-4 label">Department</div>
                                        <div class="col-lg-9 col-md-8">{{request.user.profile.department}}</div>
                                    </div>
                
                                    <div class="row">
                                        <div class="col-lg-3 col-md-4 label">Role</div>
                                        <div class="col-lg-9 col-md-8">{{request.user.role|title}}</div>
                                    </div>
                
                                </div>
                                
                                <!-- End Profile Edit Form -->
                                <div class="tab-pane fade profile-edit pt-3" id="profile-edit">
                                    <form id="profileForm" method="post">
                                        {% csrf_token %}

                                        <div class="row mb-3">
                                            <label for="id" class="col-md-4 col-lg-3 col-form-label">ID</label>
                                            <div class="col-md-8 col-lg-9">
                                                <input id="userId" type="text" class="form-control" name="user_id" value="{{request.user.id}}" disabled>
                                            </div>
                                        </div>

                                        <div class="row mb-3">
                                            <label for="profilePhoto" class="col-md-4 col-lg-3 col-form-label">Profile Photo</label>
                                            <div class="col-md-8 col-lg-9">
                                                <input id="profilePhoto" type="file" class="form-control" name="profile_photo">
                                            </div>
                                        </div>

                                        <div class="row mb-3">
                                            <label for="firstName" class="col-md-4 col-lg-3 col-form-label">First Name</label>
                                            <div class="col-md-8 col-lg-9">
                                                <input id="firstName" type="text" class="form-control" name="first_name" value="{{request.user.first_name}}" required>
                                            </div>
                                        </div>

                                        <div class="row mb-3">
                                            <label for="lastName" class="col-md-4 col-lg-3 col-form-label">Last Name</label>
                                            <div class="col-md-8 col-lg-9">
                                                <input id="lastName" type="text" class="form-control" name="last_name" value="{{request.user.last_name}}" required>
                                            </div>
                                        </div>

                                        <div class="row mb-3">
                                            <label for="email" class="col-md-4 col-lg-3 col-form-label">Email</label>
                                            <div class="col-md-8 col-lg-9">
                                                <input id="email" type="email" class="form-control" name="email" value="{{request.user.email}}" required>
                                            </div>
                                        </div>

                                        <div class="row mb-3">
                                            <label for="phoneNumber" class="col-md-4 col-lg-3 col-form-label">Phone Number</label>
                                            <div class="col-md-8 col-lg-9">
                                                <input id="phoneNumber" type="text" class="form-control" name="phone_number" value="{{request.user.profile.phone_number}}" pattern="^\d{10}$" title="Enter valid 10 digit Phone Number" required>
                                            </div>
                                        </div>

                                        <div class="row mb-3">
                                            <input id="role" type="hidden" name="role" value="{{request.user.role}}">
                                        </div>	

                                        <div class="text-center">
                                            <button type="submit" class="btn btn-primary">SAVE CHANGES</button>
                                            <a href="{% url "teacher:index-view" %}" class="btn btn-danger">CLOSE</a>
                                        </div>
                                    </form>
                                </div> 
                                
                                <!-- Change Password Form -->
                                <div class="tab-pane fade pt-3" id="profile-change-password">
                                    <form id="changePasswordForm" method="post">
                                        {% csrf_token %}
                                        
                                        <div class="row mb-3">
                                            <label for="currentPassword" class="col-md-4 col-lg-3 col-form-label">Current Password</label>
                                            <div class="col-md-8 col-lg-9">
                                                <input id="currentPassword" type="password" class="form-control" name="current_password" required>
                                            </div>
                                        </div>
                    
                                        <div class="row mb-3">
                                            <label for="newPassword" class="col-md-4 col-lg-3 col-form-label">New Password</label>
                                            <div class="col-md-8 col-lg-9">
                                                <input id="newPassword" type="password" class="form-control" name="new_password" required>
                                            </div>
                                        </div>
                    
                                        <div class="row mb-3">
                                            <label for="confirmPassword" class="col-md-4 col-lg-3 col-form-label">Confirm Password</label>
                                            <div class="col-md-8 col-lg-9">
                                                <input id="confirmPassword" type="password" class="form-control" name="confirm_password" required>
                                            </div>
                                        </div>
                    
                                        <div class="text-center">
                                            <button type="submit" class="btn btn-primary">CHANGE PASSWORD</button>
                                            <a href="{% url "teacher:index-view" %}" class="btn btn-danger">CLOSE</a>
                                        </div>
                                    </form>
                                </div>
            
                            </div>
            
                        </div>
                    </div>
                </div>

            </div>

        </section>

    </main>

{% endblock main %}  