Admin/urls.py
from django.urls import path
from Admin.views import *

app_name = 'admin'

urlpatterns = [
    path('', index_view, name='index-view'),
    path('profile/', profile_view, name='profile-view'),
    path('create/teacher/', create_teacher_view, name='create-teacher-view'),
    path('update/teacher/<int:user_id>/', update_teacher_view, name='update-teacher-view'),
    path('list/<str:role>/', list_users_view, name='list-users-view')
]

Course/urls.py
from django.urls import path
from Course.views import *

app_name = 'course'

urlpatterns = [
    path('create/', create_course_view, name='create-course-view'),    
    path('update/<int:course_id>/', update_course_view, name='update-course-view'),    
    path('delete/<int:course_id>/', delete_course_view, name='delete-course-view'),
    path('detail/<int:course_id>/', detail_course_view, name='detail-course-view'),
    path('list/courses/', list_courses_view, name='list-courses-view'),
    path('save/curriculum/<int:course_id>/', save_curriculum_view, name='save-curriculum-view'),
    path('detail/exam/<int:course_id>/', detail_exam_view, name='detail-exam-view')
]

EasyLearnApp/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('Users.urls')),
    path('admin/', include('Admin.urls', namespace='admin')),
    path('teacher/', include('Teacher.urls', namespace='teacher')),
    path('course/', include('Course.urls', namespace='course')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Course/models.py
from django.db import models
from Users.models import User
# Create your models here.

class Course(models.Model):
    id = models.BigAutoField(primary_key=True)
    thumbnail = models.ImageField(upload_to='thumbnails/', null=False, blank=False)
    title = models.CharField(max_length=255, null=False, blank=False)
    category = models.CharField(max_length=255, null=False, blank=False)
    description = models.CharField(max_length=255, null=False, blank=False)
    created_by = models.ForeignKey(User, related_name='courses', on_delete=models.CASCADE)
    created_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'Courses Table'

class Curriculum(models.Model):
    id = models.BigAutoField(primary_key=True)
    course = models.OneToOneField(Course, related_name='curriculum', on_delete=models.CASCADE)

    class Meta:
        db_table = 'Curriculums Table'

class Section(models.Model):
    id = models.BigAutoField(primary_key=True)
    curriculum = models.ForeignKey(Curriculum, related_name='sections', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, null=False, blank=False)
    order = models.PositiveIntegerField(null=False, blank=False, default=1)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'Sections Table'


ITEM_TYPE_CHOICES = (('lesson', 'lesson'), ('quiz', 'quiz'))
class CurriculumItem(models.Model):
    id = models.BigAutoField(primary_key=True)
    section = models.ForeignKey(Section, related_name='curriculum_items', on_delete=models.CASCADE)
    type = models.CharField(max_length=10, choices=ITEM_TYPE_CHOICES, null=False, blank=False)
    order = models.PositiveIntegerField(null=False, blank=False, default=1) 

    class Meta:
        db_table = 'Curriculum Items Table'

class Lesson(models.Model):
    id = models.BigAutoField(primary_key=True)
    curriculum_item = models.OneToOneField(CurriculumItem, related_name='lesson', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, null=False, blank=False)
    video_file = models.FileField(upload_to='videos/', null=False, blank=False)
    note_file = models.FileField(upload_to='notes/', null=True, blank=True)

    def __str__(self):
        return self.title
    
    class Meta:
        db_table = 'Lessons Table'

class Quiz(models.Model):
    id = models.BigAutoField(primary_key=True)
    curriculum_item = models.OneToOneField(CurriculumItem, related_name='quiz', on_delete=models.CASCADE)
    question = models.CharField(max_length=255, null=False, blank=False)
    
    class Meta:
        db_table = 'Quizzes Table'

class QuizOption(models.Model):
    id = models.BigAutoField(primary_key=True)
    quiz = models.ForeignKey(Quiz, related_name='quiz_options', on_delete=models.CASCADE)
    text = models.CharField(max_length=255, null=False, blank=False) 
    is_correct = models.BooleanField(default=False)

    class Meta:
        db_table = 'Quiz Options Table'

class Exam(models.Model):
    id = models.BigAutoField(primary_key=True)
    course = models.OneToOneField(Course, related_name='exam', on_delete=models.CASCADE)

    class Meta:
        db_table = 'Exams Table'

class Question(models.Model):
    id = models.BigAutoField(primary_key=True)
    exam = models.ForeignKey(Exam, related_name='questions', on_delete=models.CASCADE)
    text = models.CharField(max_length=255, null=False, blank=False)
    mark = models.PositiveIntegerField(null=False, blank=False, default=0)

    class Meta:
        db_table = 'Questions Table'

class Answer(models.Model):
    id = models.BigAutoField(primary_key=True)
    question = models.ForeignKey(Question, related_name='answers', on_delete=models.CASCADE)
    text = models.CharField(max_length=100, null=False, blank=False)
    is_correct = models.BooleanField(default=False)

    class Meta:
        db_table = 'Answers Table'

class WatchedContent(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(User, related_name='watched_contents', on_delete=models.CASCADE)
    item = models.ForeignKey(CurriculumItem, related_name='watched_contents', on_delete=models.CASCADE)


class Result(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(User, related_name='results', on_delete=models.CASCADE)
    course = models.ForeignKey(Course, related_name='results', on_delete=models.CASCADE)
    status = models.CharField(max_length=10, null=False, blank=False)
    obtained_marks = models.IntegerField(null=False, blank=False, default=0)
    

Course/views.py
import traceback
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib import messages
from Course.models import *
from Course.services import *
# Create your views here.

def create_course_view(request):
    if request.method == 'POST':
        try:
            thumbnail = request.FILES.get('thumbnail', '')
            title = request.POST.get('title')
            description = request.POST.get('description')
            category = request.POST.get('category')

            if Course.objects.filter(title__iexact=title).exists():
                return JsonResponse({'status':'error', 'message':'Same course title already exists.'})
            
            course = Course.objects.create(
                thumbnail = thumbnail,
                title = title,
                description = description,
                category = category,
                created_by = request.user
            )

            messages.success(request, f'{course.title} created successfully.')
            return JsonResponse({'status':'success', 'success_url':f'/course/detail/{course.id}/'})

        except Exception as error:
            return JsonResponse({'status':'error', 'message':f'ERROR: {error}'})
    return render(request, 'course/create_course.html')

def detail_course_view(request, course_id):
    course = Course.objects.get(id=course_id)
    return render(request, 'course/detail_course.html', context={'course':course})

def list_courses_view(request):
    courses = request.user.courses.all()
    return render(request, 'course/list_courses.html', context={'courses':courses})

def update_course_view(request, course_id):
    course = Course.objects.get(id=course_id)

    if request.method == 'POST':
        try:
            thumbnail = request.FILES.get('thumbnail', '')
            category = request.POST.get('category')
            title = request.POST.get('title')
            description = request.POST.get('description')

            courses = Course.objects.filter(title__iexact=title)
            if courses.exists() and course != courses[0]:
                return JsonResponse({'status':'error', 'message':'Same course title already exists.'})

            course.thumbnail = thumbnail if thumbnail != '' else course.thumbnail
            course.category = category
            course.title = title
            course.description = description
            course.save()
            messages.success(request, f'Course Information updated successfully.')
            return JsonResponse({'status':'success', 'success_url':f'/course/update/{course.id}/'})

        except Exception as error:
            return JsonResponse({'status':'error', 'message':f'ERROR: {error}'})
    return render(request, 'course/update_course.html', context={'course':course})

def delete_course_view(request, course_id):
    try:
        course = Course.objects.get(id=course_id)
        course.delete()
        messages.success(request, f'{course.title} deleted successfully.')
    except Exception as error:
        messages.error(request, f'ERROR: {error}')
    else:
        return redirect('list-courses-view')
    
def save_curriculum_view(request, course_id):
    if request.method == 'POST':
        try:
            course = Course.objects.get(id=course_id)
            curriculum, created = Curriculum.objects.get_or_create(course=course)
            
            section_ids_before = curriculum.sections.all().values_list('id', flat=True)
            section_ids_after = set()

            old_section_ids = request.POST.getlist('old_section_id[]')
            old_section_titles = request.POST.getlist('old_section_title[]')
            old_section_orders = request.POST.getlist('old_section_order[]')

            for section_id, section_title, section_order in zip(old_section_ids, old_section_titles, old_section_orders):
                section = Section.objects.get(id=int(section_id))
                section.title = section_title
                section.order = int(section_order)
                section.save()

                section_item_ids_before = section.curriculum_items.all().values_list('id', flat=True)
                section_item_ids_after = set()

                old_item_ids = request.POST.getlist(f'old_sections[{section_order}][items][item_id][]')
                old_item_types = request.POST.getlist(f'old_sections[{section_order}][items][type][]')
                old_item_orders = request.POST.getlist(f'old_sections[{section_order}][items][order][]')

                for item_id, item_type, item_order in zip(old_item_ids, old_item_types, old_item_orders):
                    curriculum_item = CurriculumItem.objects.get(id=int(item_id))
                    curriculum_item.type = item_type
                    curriculum_item.order = int(item_order)
                    curriculum_item.save()

                    if item_type == 'lesson':
                        video_id = request.POST.get(f'old_sections[{section_order}][items][{item_order}][video_id][]')
                        video_title = request.POST.get(f'old_sections[{section_order}][items][{item_order}][title][]')
                        video_file = request.FILES.get(f'old_sections[{section_order}][items][{item_order}][video_file][]',None)
                        note_file = request.FILES.get(f'old_sections[{section_order}][items][{item_order}][note_file][]', None)

                        lesson = Lesson.objects.get(id=int(video_id))
                        lesson.title = video_title
                        lesson.video_file = video_file if video_file else lesson.video_file
                        lesson.note_file = note_file if note_file else lesson.note_file
                        lesson.save()

                    else:
                        quiz_id = request.POST.get(f'old_sections[{section_order}][items][{item_order}][quiz_id][]')
                        quiz_question = request.POST.get(f'old_sections[{section_order}][items][{item_order}][question][]')
                        quiz = Quiz.objects.get(id=int(quiz_id))
                        quiz.question = quiz_question
                        quiz.save()

                        for option_number in range(1, 5):
                            option_id = request.POST.get(f'old_sections[{section_order}][items][{item_order}][options][{option_number}][option_id][]')
                            option_text = request.POST.get(f'old_sections[{section_order}][items][{item_order}][options][{option_number}][text][]')
                            is_correct = request.POST.get(f'old_sections[{section_order}][items][{item_order}][is_correct][]') == str(option_number)   

                            option = QuizOption.objects.get(id=int(option_id))
                            option.text = option_text
                            option.is_correct = is_correct
                            option.save()
                        
                    section_item_ids_after.add(int(item_id))
                    
                for id in section_item_ids_before:
                    if int(id) not in section_item_ids_after:
                        curriculum_item = CurriculumItem.objects.get(id=int(id))
                        curriculum_item.delete()

                item_types = request.POST.getlist(f'sections[{section_order}][items][type][]')
                item_orders = request.POST.getlist(f'sections[{section_order}][items][order][]')

                for item_type, item_order in zip(item_types, item_orders):
                    curriculum_item = CurriculumItem.objects.create(
                        section = section,
                        type = item_type,
                        order = int(item_order)
                    )

                    if item_type == 'lesson':
                        video_title = request.POST.get(f'sections[{section_order}][items][{item_order}][title][]')
                        video_file = request.FILES.get(f'sections[{section_order}][items][{item_order}][video_file][]')
                        note_file = request.FILES.get(f'sections[{section_order}][items][{item_order}][note_file][]', None)

                        lesson = Lesson.objects.create(
                            curriculum_item = curriculum_item,
                            title = video_title,
                            video_file = video_file,
                            note_file = note_file
                        )

                    else:
                        quiz_question = request.POST.get(f'sections[{section_order}][items][{item_order}][question][]')

                        quiz = Quiz.objects.create(
                            curriculum_item = curriculum_item,
                            question = quiz_question
                        )

                        for option_number in range(1, 5):
                            option_text = request.POST.get(f'sections[{section_order}][items][{item_order}][options][{option_number}][text][]')
                            is_correct = request.POST.get(f'sections[{section_order}][items][{item_order}][is_correct][]') == str(option_number)   
                            
                            quiz_option = QuizOption.objects.create(
                                quiz = quiz,
                                text = option_text,
                                is_correct = is_correct
                            )

                section_ids_after.add(int(section_id))

            for id in section_ids_before:
                if int(id) not in section_ids_after:
                    section = Section.objects.get(id=int(id))
                    section.delete()

            save_new_section_and_item(request, curriculum)

            messages.success(request, f'Course Curriculum for {course.title} saved successfully.')
            return JsonResponse({'status': 'success', 'success_url': f'/course/detail/{course.id}/'})
    

Course/templates/course/create_course.html
{% extends "teacher/base_site.html" %}

{% block title %} Create Course {% endblock title %}

{% block main %}

    <main id="main" class="main">

        <section class="section">

            <div class="row">
                <div class="col-12">

                    <div class="card bg-transparent">
                        <div class="card-body">

                            <h5 class="card-title">
                                <i class="bi bi-bookmark-plus-fill"></i>
                                CREATE COURSE
                            </h5>

                            <div class="card col-12 col-md-9 mx-auto">

                                <div class="card-header bg-primary-subtle text-dark fw-bold">
                                    First, let's find out what type of course you're making.
                                </div>

                                <div class="card-body p-4">

                                    {% include "components/alert.html" %}

                                    <form id="createCourseForm" method="post" class="row g-3" enctype="multipart/form-data">
                                        {% csrf_token %}

                                        <div class="col col-md-6">
                                            <label for="thumbnail" class="form-label">Course Thumbnail</label>
                                            <input id="thumbnail" type="file" class="form-control" name="thumbnail" accept="image/*" required>
                                        </div>

                                        <div class="col col-md-6">
                                            <label for="category" class="form-label">Course Category</label>
                                            <select id="category" class="form-select" name="category" required>
                                                <option value="">choose category</option>
                                                <option value="Frontend Web Development">Frontend Web Development</option>
                                                <option value="Backend Web Development">Backend Web Development</option>
                                                <option value="Data Science">Data Science</option>
                                                <option value="Mobile App Development">Mobile App Development</option>
                                            </select>
                                        </div>

                                        <div class="col-12">
                                            <label for="title" class="form-label">Title</label>
                                            <input id="title" type="text" class="form-control" name="title" required>
                                        </div>

                                        <div class="col-12">
                                            <div class="form-floating">
                                                <textarea id="description" class="form-control" name="description" placeholder="Course Description" style="height: 100px"></textarea>
                                                <label for="description">Course Description</label>
                                            </div>
                                        </div>

                                        <div class="col-12 text-center">
                                            <button type="submit" class="btn btn-primary w-50">CREATE COURSE</button>
                                        </div>
                                        
                                    </form>
                                </div>
                                
                            </div>

                        </div>
                    </div>

                </div>
            </div>

        </section>
        
    </main>

{% endblock main %}

Course/templates/course/list_courses.html
{% extends "teacher/base_site.html" %}

{% block title %} Courses List {% endblock title %}

{% block main %}

    <main id="main" class="main">

        <section class="section">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="card">

                        <div class="card-body">

                            <h5 class="card-title text-center">
                                <i class="bi bi-window-stack"></i>
                                ALL COURSES
                            </h5>

                            {% include "components/alert.html" %}
                            
                            <div class="row row-cols-2 row-cols-lg-3 g-2 g-lg-3">

                                {% for course in courses %}

                                    <div class="col">
                                        <div class="card h-100">

                                            <img src="{{course.thumbnail.url}}" class="card-img-top h-100" alt="Course Thumbnail">

                                            <div class="card-body border border-dark shadow">
                                                <h5 class="card-title">{{course.title}} <br>
                                                    <span>@{{course.created_date}}<span>
                                                </h5>

                                                <p class="card-text">
                                                    {{course.description|truncatechars:68}}
                                                </p>
                                                
                                                <a href="{% url "course:detail-course-view" course.id %}" class="btn btn-primary w-100">
                                                    <i class="bi bi-gear"></i>
                                                    Manage Course
                                                </a>
                                            </div>
                                            
                                        </div>
                                    </div>
                                {% endfor %}
                                
                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </section>

    </main>

{% endblock main %}

Course/templates/course/test.html
<div class="col-12 question-item" data-question-number="${order}">
    <div class="row">

        <div class="col-11">

            <div class="row g-3 justify-content-end">
                <div class="col-12">
                    <div class="row">
                        <label class="col-sm-2 col-form-label question-label">(${order}) Question :</label>
                        <div class="col-sm-7">
                            <input type="text" class="form-control" name="question[]" required>
                        </div>
                        <div class="col-sm-3">
                            <input type="number" class="form-control" name="mark[]" placeholder="Marks" required>
                        </div>
                    </div>
                </div>

                <!-- Options -->
                <div class="col-10">
                    <div class="row g-2">
                        ${createAnswerField(order, 1)}
                        ${createAnswerField(order, 2)}
                        ${createAnswerField(order, 3)}
                        ${createAnswerField(order, 4)}
                    </div>
                </div>
            </div>
            
        </div>

        <div class="col-1 text-center">
            <i class="bi bi-trash text-danger fs-5 remove-question"></i>
        </div>
    </div>

</div>

Course/templates/course/update_course.html
{% extends "teacher/base_site.html" %}

{% block title %} Update Course {% endblock title %}

{% block main %}

    <main id="main" class="main">

        <section class="section">

            <div class="row justify-content-lg-center">
                <div class="col-12">

                    <div class="card">

                        <div class="card-body">

                            <h5 class="card-title text-center">
                                <i class="bi bi-bookmark-plus-fill"></i>
                                UPDATE COURSE PAGE
                            </h5>

                            <div class="card col-12 col-md-9 mx-auto">

                                <div class="card-body">

                                    {% include "components/alert.html" %}

                                    <div class="d-flex justify-content-between align-items-center">

                                        <h5 class="card-title fs-4">{{course.title}} <br> 
                                            <span>@ {{course.created_date}}<span>
                                        </h5>
                                        
                                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#verticalycentered">
                                            <i class="bi bi-trash"></i>
                                        </button>

                                        <div class="modal fade text-center" id="verticalycentered" tabindex="-1">
                                            <div class="modal-dialog modal-dialog-centered">
                                                <div class="modal-content">

                                                    <div class="modal-header">
                                                        <h5 class="modal-title">CONFIRM DELETE</h5>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                    </div>

                                                    <div class="modal-body">
                                                        <h5 class="card-title mb-0 pb-2">{{course.title}}</h5>
                                                        Are you sure you want to delete this course?
                                                    </div>

                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">CLOSE</button>
                                                        <a href="{% url "course:delete-course-view" course.id %}" class="btn btn-danger">DELETE</a>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>

                                    </div>

                                    <img src="{{course.thumbnail.url}}" class="card-img-top" alt="Course Thumbnail">

                                    <form id="updateCourseForm" method="post" class="row g-3 mt-3" enctype="multipart/form-data">
                                        {% csrf_token %}

                                        <input id="courseId" type="hidden" name="course_id" value="{{course.id}}">

                                        <div class="col col-md-6">
                                            <label for="thumbnail" class="form-label">Course Thumbnail</label>
                                            <input id="thumbnail" class="form-control" type="file" accept="image/*" name="thumbnail">
                                        </div>

                                        <div class="col col-md-6">
                                            <label for="category" class="form-label">Course Category</label>
                                            <select id="category" class="form-select" name="category" required>
                                                <option {% if course.category == 'Frontend Web Development' %}selected{% endif %} value="Frontend Web Development">Frontend Web Development</option>
                                                <option {% if course.category == 'Backend Web Development' %}selected{% endif %} value="Backend Web Development">Backend Web Development</option>
                                                <option {% if course.category == 'Data Science' %}selected{% endif %} value="Data Science">Data Science</option>
                                                <option {% if course.category == 'Mobile App Development' %}selected{% endif %} value="Mobile App Development">Mobile App Development</option>
                                            </select>
                                        </div>

                                        <div class="col-12">
                                            <label for="title" class="form-label">Title</label>
                                            <input id="title" type="text" class="form-control" name="title" value="{{course.title}}" required>
                                        </div>

                                        <div class="col-12">
                                            <div class="form-floating">
                                                <textarea id="description" class="form-control" name="description" placeholder="Course Description" style="height: 100px">{{ course.description }}</textarea>
                                                <label for="description">Course Description</label>
                                            </div>
                                        </div>

                                        <div class="col-12 text-center">
                                            <button type="submit" class="btn btn-primary w-50">UPDATE COURSE</button>
                                            <a href="{% url "course:detail-course-view" course.id %}" class="btn btn-danger">CLOSE</a>
                                        </div>
                                        
                                    </form>
                                </div>
                                
                            </div>
                        </div>

                    </div>
                    
                </div>
            </div>

        </section>

    </main>

{% endblock main %}

    